---
 - name: ensure os is up to date
   apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

 - name: install packages
   apt: pkg={{ item }} state=present
   with_items:
    - bash-completion
    - curl
    - exiftool
    - fuse
    - git
    - htop
    - iftop
    - iotop
    - jq
    - lynx
    - mc
    - ncdu
    - nmap
    - openssh-server
    - python
    - reptyr
    - screen
    - smartmontools
    - sudo
    - tmux
    - tree
