---
- name: Update apt cache 
  apt: update_cache=yes 
  become: yes 
 
- name: Install dependencies for docker-debian
  apt:  
    name: [ 'aptitude', 'apt-transport-https', 'ca-certificates', 'gnupg2', 'software-properties-common' ]
    state: latest 
  become: yes 

- name: Add Docker GPG key
  apt_key: 
    url: https://download.docker.com/linux/debian/gpg
  become: yes 

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
  become: yes 

- name: Install Docker
  apt:
    name: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
  become: yes
  

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
    
- name: link /usr/local/bin/docker-compose
  become: yes
  become_user: root
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
- name: copy docker-compose files
  copy:
   dest: ""
    src: ""
    mode: 
